# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ricardo Maiostri
tagline:          'Software Passionate'
description:      'Guides, tips and thoughts related to the software development process. Java, Scala, Javascript, functional programming and other stuff.'
baseurl:          /

author:
  name:           'Ricardo Maiostri'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/maiostri
